-- MySQL Script generated by MySQL Workbench
-- Sat Jun  2 16:44:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackson` DEFAULT CHARACTER SET utf8 ;
USE `hackson` ;

-- -----------------------------------------------------
-- Table `hackson`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`user` (
  `openid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `role` VARCHAR(45) NULL,
  `family_id` VARCHAR(45) NULL,
  PRIMARY KEY (`openid`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackson`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`family` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `count` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackson`.`scene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`scene` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackson`.`templete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`templete` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `scene_id` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackson`.`markday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`markday` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `name` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `family_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `hackson`.`imageList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`imageList` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `to_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackson`.`voiceList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`voiceList` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `uri` VARCHAR(45) NULL,
  `to_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackson`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackson`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `from_id` VARCHAR(45) NULL,
  `to_id` VARCHAR(45) NULL,
  `templete_type` INT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
